### ISSUE TITLE
Unable to start vite server once I added this plugin

### ISSUE THREAD

**Issue by nwlucas** [JohnCampionJr/vite-plugin-vue-layouts#39]
Following the readme and adding this plugin results in an error when trying to start the vite dev server. Simply removing that last plugin call, and of course all code added to use it in other files and the server starts up fine again.

```bash
╰─ yarn vite-tauri dev                                                                                                                               ─╯
yarn run v1.22.11
$ vite-tauri dev
23:22:04 PM [vite-plugin-tauri]  Starting Vite dev server...
failed to load config from /vite.config.ts
file:///vite.config.ts.js?t=1630466524160:15
    Layouts({
    ^

TypeError: Layouts is not a function
    at file:///vite.config.ts.js?t=1630466524160:15:5
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/node_modules/vite/dist/node/chunks/dep-972722fa.js:75819:31)
    at async resolveConfig (node_modules/vite/dist/node/chunks/dep-972722fa.js:75434:28)
    at async createServer (node_modules/vite/dist/node/chunks/dep-972722fa.js:73957:20)
    at async dev (node_modules/vite-plugin-tauri/bin/index.js:156:18)
    at async node_modules/vite-plugin-tauri/bin/index.js:184:7
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And for reference here are some files:
`vite.config.ts`
```typescript
import { defineConfig } from 'vite'
import Vue from '@vitejs/plugin-vue'
import Pages from 'vite-plugin-pages'
import Layouts from 'vite-plugin-vue-layouts'
import { resolve } from 'path'

// https://vitejs.dev/config/
export default defineConfig({
	resolve: {
		alias: {
			'@': resolve(__dirname, 'src')
		}
	},
	plugins: [
		Vue(),
		Layouts({
			layoutsDir: 'src/layouts'
		}),
		Pages({
			exclude: ['**/components/*.vue'],
			pagesDir: [
				{ dir: 'src/pages', baseRoute: '' },
				{ dir: 'src/features/**/pages', baseRoute: 'features' },
				{ dir: 'src/admin/pages', baseRoute: 'admin' }
			]
		})
	]
})
```
`tsconfig.json`
```json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "esnext",
		"moduleResolution": "node",
		"strict": true,
		"jsx": "preserve",
		"sourceMap": true,
		"importHelpers": true,
		"skipLibCheck": true,
		"resolveJsonModule": true,
		"allowSyntheticDefaultImports": true,
		"experimentalDecorators": true,
		"esModuleInterop": true,
		"pretty": true,
		"baseUrl": ".",
		"paths": {
			"@/*": ["./src/*"]
		},
		"lib": ["esnext", "dom", "DOM.Iterable", "ScriptHost"],
		"types": ["vite/client", "vite-plugin-vue-layouts/client", "vite-plugin-pages/client"]
	},
	"include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
	"exclude": ["node_modules", "**/*.spec.ts"]
}
```

**Comment by JohnCampionJr** [comment]
No idea, it works for me and others.  Can you create a reproduction repo?

**Comment by nwlucas** [comment]
I just publish a clone repo so you can see it.

[Repo that has the issue](https://github.com/nwlucas/helios).

Commenting out the relevant lines for this plugin in `vite.config.ts` and also from `code/router.ts` and the server starts up.

**Comment by JohnCampionJr** [comment]
OK, I see the error, but I'm completely stumped.  The one thing I see in VS Code when comparing it to Vitesse is that something is creating a vite.config.ts.js file.  In the standard templates, that file is not created.  Vite doesn't need it. I feel like that is the problem but I can't figure out why that file is being created here and not in the standard templates.

**Comment by JohnCampionJr** [comment]
Figured it out.  Take this out of package.json

```
    "type": "module",
```

That seems to break all sorts of things
